packages:
  - 'packages/*'

allowBuilds:
  '@tailwindcss/oxide': true
  bcrypt: true
  better-sqlite3: true
  bufferutil: true
  es5-ext: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@nextpress-org/sdk@0.2.0'
